[package]
name = "snake"
version = "0.1.4"
authors = ["kschat <kyleschattler@gmail.com>"]
edition = "2024"
license = "MIT"

[dependencies]
crossterm = "0.29"
rand = "0.9.2"
impl_ops = "0.1.1"
num-traits = "0.2"
anyhow = "1.0.100"
structopt = "0.3.26"
unicode-segmentation = "1.12.0"
